apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    # Tells this deployment which Pods it's supposed to manage
    selector:
        matchLabels:
            component: postgres
    # All pods created by this deployment will have these attributes
    template:
        metadata:
            labels:
                component: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres #use generic postgres image from DockerHub
                  # port that we'll expose/open from this pod/container to outside world
                  ports:
                      - containerPort: 5432
