# Config file for cert manager helm chart to create https certificate
#
# Instructions: https://cert-manager.io/docs/configuration/acme/
# apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: "chad.burkins@gmail.com"
        privateKeySecretRef:
            name: letsencrypt-prod
        # Select method for obtaining certificate
        # http01: {}
        solvers:
            - http01:
                  ingress:
                      class: nginx
