apiVersion: v1
# This is advertisement that will get attached to a Pod config
# Will cause kubernetes to attempt to find storage
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
