apiVersion: v1
kind: Service
metadata:
    name: redis-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: redis
    ports:
        - port: 6379 #front-end port exposed to other pods in the clusters
          targetPort: 6379 #port exposed on the back-end target pod
